@startuml
autonumber

skinparam sequence {
ArrowColor gray
ActorBorderColor gray
LifeLineBorderColor black
}
skinparam shadowing false
hide footbox

participant 民眾 #d1ebf1
participant HPA  #D5E8D4
民眾 -> HPA: 情境1：填寫自填調查表
民眾 -> HPA: 情境2：上傳運動紀錄
民眾 -> HPA: 情境3：上傳飲食紀錄
民眾 -> HPA: 情境4：編輯身體數值
民眾 -> HPA: 情境5：上傳飲水紀錄
民眾 -> HPA: 情境6：風險評估
民眾 -> HPA: 情境7：目標管理
@enduml